default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: beatr_development

test:
  <<: *default
  database: beatr_test

production:
  <<: *default
  database: beatr_production
  username: beatr
  password: <%= ENV['BEATR_DATABASE_PASSWORD'] %>
